Openschool/Openschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import  url
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cuentas.urls')),
    path('foros/', include('foros.urls')),
    path('articulos/', include('articulos.urls')),
     path('blog/', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

Openschool/articulos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'articulos'

urlpatterns = [
    path('', views.index, name='index'),
    path('preguntas/<int:Carrera>', views.detail, name='detail'),
    path('CrearPregunta/<int:Materiaid>/', views.ArticuloFormA, name='ArticuloFormA'),
    path('<int:Preguntaid>/results/', views.results, name='results'),
    path('<int:Preguntaid>/results/<int:Comentariosid>', views.resultsH, name='resultsH'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Openschool/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'

urlpatterns = [
path('blog',views.blogs, name='blog'),
]

Openschool/cuentas/urls.py
from django.urls import path
from . import views

app_name = 'cuentas'


urlpatterns = [
    path('', views.index, name='index'),
    path('registro', views.registro, name='registro'),
    path('login', views.login_user, name='login_user'),
    path('logout', views.logout_user, name='logout_user'),

    ]

Openschool/foros/urls.py
from django.urls import path

from . import views
app_name = 'foro'

urlpatterns = [
    path('', views.index, name='index'),
    path('preguntas/<int:Carrera>', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:Preguntaid>/results/<int:Comentariosid>', views.resultsH, name='resultsH'),
    path('<int:Preguntaid>/results/', views.results, name='results'),
    path('CrearPregunta/<int:Materiaid>/', views.PreguntaFormA, name='PreguntaFormA'),
    path('buscar',views.Buscar,name='buscar'),
]

Openschool/cuentas/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Usuarios(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,default=1)
    edad = models.IntegerField(null=True)
    perfil= models.ImageField()



def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Usuarios.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

Openschool/cuentas/forms.py
from django import forms
from cuentas.models import Usuarios
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from foros.models import Inscripcion

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True,
        widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(
        label=("Contraseña"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class':'form-control'}),
        help_text="",)
    password2 = forms.CharField(
        label=("Confirma contraseña"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class':'form-control'}),
        help_text="",)
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
        labels = {
        'username': 'Usuario',
        'first_name':'Nombre',
        'last_name':'Apellido',

        }
        help_text={
        'password1':"",
        'password2':"",
        }
        widgets={
        'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),

        }

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


        return user

class Datos(forms.ModelForm):

    class Meta:
        model = Usuarios
        fields = ['edad','perfil']

        labels={'edad':'Edad'}

        widgets={'edad':forms.TextInput(attrs={'class':'form-control'})}

Openschool/cuentas/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import UserForm, Datos
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.db import transaction
from django.urls import reverse
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import logout

# Create your views here.
def index(request):
    return render(request,'cuentas/index.html')

@transaction.atomic
def registro(request):
    if request.method =='POST':
        form = UserForm(request.POST)
        Datos_form = Datos(request.POST,request.FILES or None)

        if form.is_valid() and Datos_form.is_valid():
            user=form.save()
            username = request.POST['username']
            password = request.POST['password1']

            user.refresh_from_db()
            Datos_form = Datos(request.POST,request.FILES or None,instance=user.usuarios)
            Datos_form.full_clean()
            Datos_form.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                return render(request, 'cuentas/index.html')
            return redirect(reverse('cuentas:index'))
    else:
        form = UserForm()
        Datos_form = Datos()
        args = {'UserForm_form': form,'Datos_form': Datos_form}
        return render(request, 'cuentas/reg_form.html', args)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'cuentas/index.html')
            else:
                return render(request, 'cuentas/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'cuentas/login.html', {'error_message': 'Invalid login'})
    return render(request, 'cuentas/login.html')

def logout_user(request):
    logout(request)
    return render(request, 'cuentas/login.html')

Openschool/cuentas/templates/cuentas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>OpenSchool</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="css/estilos.css">

</head>
<body>
	<header>
		<!---------Barra de Menu horizontal-------->
	        <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
            <div class="container">
              <a class="navbar-brand" href="{% url 'cuentas:index' %}">OpenSchool</a>
            </div>
          </nav>
	</header>
    <!-----Contenedor de cuerpo de la pagina------>
	<div class="container">
        {% block body %}
        {% endblock %}
	  </div>
	</div>
</body>
</html>

Openschool/cuentas/templates/cuentas/buscar.html
{% extends 'cuentas/index2.html' %}
{% block body %}
 {% if Preguntas %}
    {% for Pregunta in Preguntas %}
    <div style="margin-top: 10px;">
            <div >
             <li style="display: block; text-decoration: none;"><a href="{% url 'foro:results' Pregunta.id %}" style="color:white; " class="btn btn-lg btn-block btn-primary" role="button" >{{Pregunta.Texto_Pregunta}}</a></li>
            </div>
        </div>
        {% endfor %}
 {% elif Articulos %}
    {% for Articulo in Articulos %}
    <div style="margin-top: 10px;">
            <div >
             <li style="display: block; text-decoration: none;"><a href="{% url 'articulos:results' Articulo.id %}" style="color:white; " class="btn btn-lg btn-block btn-primary" role="button" >{{Articulo.Titulo}}</a></li>
            </div>
        </div>
        {% endfor %}
 {% else %}
 <h2>No se encontro nada</h2>
 {% endif %}
{% endblock %}

Openschool/cuentas/templates/cuentas/chat.html
{% extends 'cuentas/index2.html' %}
{% block body %}
<div id="Chat" class="panel panel-default">
	<div class="panel-heading">Chat</div>
	<div id="lista-msj" class="panel-body">
		<ul id="lista" class="list-group">
			{% for Chat  in chats %}
			   {% if Chat.user == request.user %}
			    <li class="text-right list-group-item">{{obj.message}}</li>
			   {% else %}
			    <li class="text-left list-group-item">{{obj.message}}</li>
			   {% endif %}
			{% empty %}
			  <li class="text-right list-group-item">No hay mensajes</li>
			{% endfor %}
			<script>
				var chatlist = document.getElementById('lista-msj');
				chatlist.scrollTop=chatlist.scrollHeight;
			</script>
		</ul>
	</div>
</div>
<form id="forma-chat" method="post" action="{% url 'cuentas:post'%}">
	<div id="chat-bottom" class="input-group">
		<input type="text" name="chat-msj" id="chat-msj" class="form-control"/>
		<span class="input-group-btn">
			{% csrf_token %}
			<input type="submit" class="btn btn-default" id="Enviar" value="Enviar"/>
	</div>
</form>
{% endblock %}

Openschool/cuentas/templates/cuentas/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>OpenSchool</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

</head>
<body style="background-color: #f2f2f2">
  <header>
    <!---------Barra de Menu horizontal-------->
   <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
      <div class="container">
          <a class="navbar-brand" href="{% url 'foro:index' %}">OpenSchool</a>
          <form class="form-inline" action="{% url 'foro:buscar' %}" method="POST" style="position: relative; right:100px">{% csrf_token %}
            <input class="form-control" name="buscalo" type="text" placeholder="Buscar..." >
            <button class="btn btn-info" type="submit" >Buscar</button>
          </form>
          <ul class="navbar-nav">
          {% if not user.is_authenticated %} 
            <li class="nav-item" >
             <a class="nav-link" href="{% url 'cuentas:registro' %}">Registrate!</a>
            </li>
            <li class="nav-item" ">
              <a class="nav-link" href="{% url 'cuentas:login_user' %}">Iniciar Sesión</a>
            </li>
          {%else%}
              <div class="dropdown">
               <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Cuenta
               </button>
               <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'blog:blog' %}">Blog</a>
                <a class="dropdown-item" href="{% url 'cuentas:logout_user' %}">Logout</a>
               </div>
             </div>
            </li>
          {% endif%}
          </ul>
      </div>
   </nav>

  </header>
    <!-----Contenedor de cuerpo de la pagina------>
  <div class="container">
    <div class="row">
      <!-----Primera seccion de la pagina(izquierda)------>
      <div class="col-md-3 list-group" style="margin-top: 10px;">
           
            <a href="{% url 'foro:index' %}" class="list-group-item list-group-item-primary">Foros</a>
            <a href="{% url 'articulos:index' %}" class="list-group-item list-group-item-primary">Artículos</a><br>
            <label>Herramientas</label>
             <a href="http://www.wolframalpha.com/" class="list-group-item list-group-item-primary">WolframAlpha</a>
            <a href="https://www.arenasimulation.com/" class="list-group-item list-group-item-primary">Arena Simulatior</a>
             <a href="https://www.texstudio.org/" class="list-group-item list-group-item-primary">TeXstudio</a>
            <a href="http://www.malmath.com/" class="list-group-item list-group-item-primary">MalMath</a>
             <a href="https://www.geogebra.org/?lang=es" class="list-group-item list-group-item-primary">GeoGebra</a>
            <a href="http://www.ni.com/multisim/try/esa/" class="list-group-item list-group-item-primary">Multisim</a>

      </div>
            <div class="col-md-9 list-group-item list-group-item-primary" style="margin-top: 10px;">
                 <h2>Bienvenidos!!</h2>
                 <img src="{% static 'imagenes/open.png' %}" class="rounded" width="300" height="250" style="margin-left: 220px;" >
                 <br><br>
                 <p>"Somos una red social que ayuda a los usuarios proporcionandoles herramientas de trabajo y una comunidad para la resolución de dudas una materia a través de foros, de una manera mas amigable".</p>
            </div>
      </div>
  </div>
</body>
</html>

Openschool/cuentas/templates/cuentas/index2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>OpenSchool</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <script src="{% static 'chat.js' %}"></script>

</head>
<body style="background-color: #f2f2f2">
  <header>
    <!---------Barra de Menu horizontal-------->
   <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
      <div class="container">
          <a class="navbar-brand" href="{% url 'foro:index' %}">OpenSchool</a>
          <form class="form-inline" action="{% url 'foro:buscar' %}" method="POST" style="position: relative; right:100px">{% csrf_token %}
            <input class="form-control" name="buscalo" type="text" placeholder="Buscar..." >
            <button class="btn btn-info" type="submit">Buscar</button>
          </form>
          <ul class="navbar-nav">
          {% if not user.is_authenticated %} 
            <li class="nav-item" >
             <a class="nav-link" href="{% url 'cuentas:registro' %}">Registrate!</a>
            </li>
            <li class="nav-item" ">
              <a class="nav-link" href="{% url 'cuentas:login_user' %}">Iniciar Sesión</a>
            </li>
          {%else%}
              <div class="dropdown">
               <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Cuenta
               </button>
               <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'blog:blog' %}">Blog</a>
                <a class="dropdown-item" href="{% url 'cuentas:logout_user' %}">Logout</a>
               </div>
             </div>
            </li>
          {% endif%}
          </ul>
      </div>
   </nav>

  </header>
    <!-----Contenedor de cuerpo de la pagina------>
  <div class="container">
    <div class="row">
      <!-----Primera seccion de la pagina(izquierda)------>
      <div class="col-md-3 list-group" style="margin-top: 10px;">
           
            <a href="{% url 'foro:index' %}" class="list-group-item list-group-item-primary">Foros</a>
            <a href="{% url 'articulos:index' %}" class="list-group-item list-group-item-primary">Artículos</a><br>
            <label>Herramientas</label>
             <a href="http://www.wolframalpha.com/" class="list-group-item list-group-item-primary">WolframAlpha</a>
            <a href="https://www.arenasimulation.com/" class="list-group-item list-group-item-primary">Arena Simulatior</a>
             <a href="https://www.texstudio.org/" class="list-group-item list-group-item-primary">TeXstudio</a>
            <a href="http://www.malmath.com/" class="list-group-item list-group-item-primary">MalMath</a>
             <a href="https://www.geogebra.org/?lang=es" class="list-group-item list-group-item-primary">GeoGebra</a>
            <a href="http://www.ni.com/multisim/try/esa/" class="list-group-item list-group-item-primary">Multisim</a>

      </div>
            <div class="col-md-9 list-group-item list-group-item-primary" style="margin-top: 10px;">
                 
              {% block body %}
              
              {% endblock %}
                </div>
            </div>
      </div>
  </div>
  <div>
</body>
</html>

Openschool/cuentas/templates/cuentas/login.html
{% extends 'cuentas/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class=" col-md-4" style="margin-top: 50px;margin-left: 350px">
            <div class="card bg-light">
                <div class="card-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'cuentas:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="id_username">Username:</label>
                            <input id="id_username" class="form-control" maxlength="30" name="username" type="text" required>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="id_password">Password:</label>
                            <input id="id_password" class="form-control" maxlength="30" name="password" type="password" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'cuentas:registro' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Openschool/cuentas/templates/cuentas/mensajes.html
{% for Chat  in chats %}
			   {% if Chat.user == request.user %}
			    <li class="text-right list-group-item">{{obj.message}}</li>
			   {% else %}
			    <li class="text-left list-group-item">{{obj.message}}</li>
			   {% endif %}
			{% empty %}
			  <li class="text-right list-group-item">No hay mensajes</li>
			{% endfor %}

Openschool/cuentas/templates/cuentas/reg_form.html
{% extends 'cuentas/base.html' %}
{% block body %}
   <div class="container card bg-light" style="margin-top: 10px; margin-bottom: 10px;width: 50%" >
     <h1 style="text-align: center;">Registro</h1>
         <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    {{ UserForm_form.as_p }}
                    {{ Datos_form.as_p }}
                    <button type="submit" class="btn btn-block btn-lg btn-success" style="margin-bottom: 10px;">Crear</button>
        </form>
   </div>
                {% endblock %}