Openschool/Openschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import  url
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cuentas.urls')),
    path('foros/', include('foros.urls')),
    path('articulos/', include('articulos.urls')),
     path('blog/', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

Openschool/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'

urlpatterns = [
path('blog',views.blogs, name='blog'),
]

Openschool/foros/urls.py
from django.urls import path

from . import views
app_name = 'foro'

urlpatterns = [
    path('', views.index, name='index'),
    path('preguntas/<int:Carrera>', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:Preguntaid>/results/<int:Comentariosid>', views.resultsH, name='resultsH'),
    path('<int:Preguntaid>/results/', views.results, name='results'),
    path('CrearPregunta/<int:Materiaid>/', views.PreguntaFormA, name='PreguntaFormA'),
    path('buscar',views.Buscar,name='buscar'),
]

Openschool/foros/models.py
from django.db import models

import datetime
from django.utils import timezone
from cuentas.models import Usuarios
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
class Carrera(models.Model):
    Nombre_Carrera = models.CharField(max_length=30)

    def __str__(self):
        return self.Nombre_Carrera
@receiver(post_save, sender=Carrera)
def save_Carrera(sender, instance, **kwargs):
    if kwargs['created']:
        Materia.objects.create(Carrera=instance,Nombre_Materia='Foro_General')


class Materia(models.Model):
    Nombre_Materia = models.CharField(max_length=200)
    Carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)

    def __str__(self):
        return self.Nombre_Materia

class Inscripcion(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    Carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)


class Pregunta(models.Model):
    Materia = models.ForeignKey(Materia, on_delete=models.CASCADE,default=1)
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    Texto_Pregunta = models.CharField(max_length=200)
    Fecha_Publicacion = models.DateTimeField('date published',auto_now=True)
    Estado = models.BooleanField(default=False)
    def was_published_recently(self):
        return self.Fecha_Publicacion >= timezone.now() - datetime.timedelta(days=1)


    def __str__(self):
        return self.Texto_Pregunta



class Articulo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    Materia = models.ForeignKey(Materia, on_delete=models.CASCADE,default=1)
    Pdf_articulo = models.FileField()
    Fecha_Publicacion = models.DateTimeField('date published',auto_now=True)
    Titulo = models.CharField(max_length=200)

    def __str__(self):
        return self.Titulo

class Respuesta_Pregunta(models.Model):
    Pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    Texto_Respuesta = models.CharField(max_length=200)
    Comentarios = models.ForeignKey('self', on_delete=models.CASCADE,null=True,blank =True)
    Fecha_Publicacion = models.DateTimeField('date published',auto_now=True)
    def __str__(self):
        return self.Texto_Respuesta


class Comentario_Articulo(models.Model):
    Articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE)
    Texto_Respuesta = models.CharField(max_length=200)
    Comentarios = models.ForeignKey('self', on_delete=models.CASCADE,null=True,blank =True)
    Fecha_Publicacion = models.DateTimeField('date published',auto_now=True)
    def __str__(self):
        return self.Texto_Respuesta

Openschool/foros/forms.py
from django import forms
from django.contrib.auth.models import User
from foros.models import Pregunta,Respuesta_Pregunta




class PreguntaForm(forms.ModelForm):

    class Meta:
        model = Pregunta
        fields = (
            'Texto_Pregunta',
        )
        labels={
        'Texto_Pregunta':'Pregunta',
        }
        widgets={
         'Texto_Pregunta':forms.TextInput(attrs={'class':'form-control'}),
        }

class RespuestaForm(forms.ModelForm):

    class Meta:
        model = Respuesta_Pregunta
        fields = (
            'Texto_Respuesta',
        )

        labels={
        'Texto_Respuesta':'Comentar',
        }

        widgets={
         'Texto_Respuesta':forms.TextInput(attrs={'class':'form-control'}),
        }

Openschool/foros/views.py
# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.conf import settings
#
from django.core.files.storage import FileSystemStorage
#impoorta la tabla pregunta
from .models import Pregunta, Carrera,Materia,Respuesta_Pregunta,Articulo
# Create your views here.
#libreria que manda errores si pasan cosas que no esperamos
#es para ser try cath
from django.http import Http404,HttpResponse
from .forms import PreguntaForm,RespuestaForm
#Creacion del formulario
import datetime
from django.utils import timezone
def index(request):
    Carreras = Carrera.objects.all()
    return render(request,'foro/index.html',{'Carreras': Carreras})


def detail(request,Carrera):
    Materias = Materia.objects.get(Carrera_id = Carrera,Nombre_Materia= 'Foro_General')

    Preguntas = Pregunta.objects.filter(Materia_id= Materias.id)
    Preguntas = Preguntas.order_by('-Fecha_Publicacion')[:5]

    return render(request,'foro/detail.html',{'Preguntas': Preguntas,'Materias': Materias})

def results(request, Preguntaid):
    Comentarios = Respuesta_Pregunta.objects.filter(Pregunta_id= Preguntaid,Comentarios__isnull=True)
    Comentarios = Comentarios.order_by('-Fecha_Publicacion')[:5]
    Preguntas= Pregunta.objects.get(pk=Preguntaid)
    Respuesta_Form = RespuestaForm()
    if request.method == 'POST':
        if  request.user.is_authenticated:
            Respuesta_Form = RespuestaForm(request.POST)
            if Respuesta_Form.is_valid():
                Preguntas = Pregunta.objects.get(id = Preguntaid)
                Respuesta = Respuesta_Form.save(commit=False)
                Respuesta.user = request.user
                Respuesta.Texto_Respuesta = request.POST['Texto_Respuesta']
                Respuesta.Pregunta = Preguntas
                Respuesta.save()
                return render(request,'foro/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'Preguntas':Preguntas,'Respuesta_Form': Respuesta_Form})
    else:
        Respuesta_Form = RespuestaForm()

    return render(request,'foro/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'Preguntas':Preguntas,'Respuesta_Form': Respuesta_Form})

def resultsH(request,Preguntaid,Comentariosid):
    Comentario = Respuesta_Pregunta.objects.filter(Pregunta_id= Preguntaid,Comentarios=Comentariosid)
    Comentario = Comentario.order_by('-Fecha_Publicacion')[:5]
    ComentarioP= Respuesta_Pregunta.objects.get(pk=Comentariosid)
    Respuesta_Form = RespuestaForm()
    if request.method == 'POST':
        if  request.user.is_authenticated:
            Respuesta_Form = RespuestaForm(request.POST)
            if Respuesta_Form.is_valid():
                Preguntas = Pregunta.objects.get(id = Preguntaid)
                Respuesta = Respuesta_Form.save(commit=False)
                Respuesta.user = request.user
                Respuesta.Comentarios = ComentarioP
                Respuesta.Texto_Respuesta = request.POST['Texto_Respuesta']
                Respuesta.Pregunta = Preguntas
                Respuesta.save()
                return render(request,'foro/Comentarios.html',{'Comentarios': Comentario,'Preguntaid':Preguntaid,'ComentarioP':ComentarioP,'Respuesta_Form': Respuesta_Form})
    return render(request,'foro/Comentarios.html',{'Comentarios': Comentario,'Preguntaid':Preguntaid,'ComentarioP':ComentarioP,'Respuesta_Form': Respuesta_Form})

from .models import Pregunta, Carrera,Materia,Respuesta_Pregunta

def PreguntaFormA(request,Materiaid):
    Preguntas = Pregunta.objects.filter(Materia_id= Materiaid)
    Preguntas = Preguntas.order_by('-Fecha_Publicacion')[:5]
    if not request.user.is_authenticated:
        return render(request, 'cuentas/login.html')
    if request.method == 'POST':
        Pregunta_Form = PreguntaForm(request.POST)
        if Pregunta_Form.is_valid():
            Materias = Materia.objects.get(id = Materiaid)
            Preguntad = Pregunta_Form.save(commit=False)
            Preguntad.user = request.user
            Preguntad.Texto_Pregunta = request.POST['Texto_Pregunta']
            Preguntad.Materia = Materias
            Preguntad.save()
            return render(request,'foro/detail.html',{'Preguntas': Preguntas,'Materias': Materias})
    else:
        Pregunta_Form = PreguntaForm()
        args = {'Pregunta_Form': Pregunta_Form}
    return render(request,'foro/FormPregunta.html',args)

def Buscar(request):
    buscar=request.POST['buscalo']
    Preguntas=Pregunta.objects.filter(Texto_Pregunta__contains=buscar)
    if Preguntas:
        return render (request,'cuentas/buscar.html',{'Preguntas':Preguntas})
    else:
        Articulos=Articulo.objects.filter(Titulo__contains=buscar)
        return render (request,'cuentas/buscar.html',{'Articulos':Articulos})

Openschool/foros/templates/foro/Comentarios.html
{% extends 'cuentas/index2.html' %}
{% block body %}
{% if Preguntas %}
<div class="card bg-primary" style="margin-top: 10px;">
  <div class="card-body">
  <h2 style="color:white;">{{Preguntas.Texto_Pregunta}}</h2>
  </div>
</div>
{% else %}
<div class="card bg-primary" style="margin-top: 10px;">
  <div class="card-body">
  <h2 style="color:white;">{{ComentarioP.Texto_Respuesta}}</h2>
  </div>
</div>
{% endif %}
	{% if Comentarios %}
      <div class="list-group-item list-group-item-primary">
     {% for Respuesta_Pregunta in Comentarios %}
        <li style="display: block; text-decoration: none;"><a href="{% url 'foro:resultsH' Preguntaid Respuesta_Pregunta.id %}" class="btn btn-lg btn-block btn-info" role="button" style="text-align: left;">{{Respuesta_Pregunta.Texto_Respuesta}}</a></li>
      </div>
      <div class="list-group-item list-group-item-primary">
        <form method="post">
     {% endfor %}
        {% csrf_token %}
        {{ Respuesta_Form.as_p }}
        <button type="submit" class="btn btn-lg btn-info">Submit</button>
        </form>
      </div>
	{% else %}
	<div class="list-group-item list-group-item-primary">
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ Respuesta_Form.as_p }}
        <button type="submit" class="btn btn-lg btn-info">Submit</button>
      </form>
    </div>
  </div>

	{% endif %}
{% endblock %}

Openschool/foros/templates/foro/ComentariosH.html
{% extends 'cuentas/index2.html' %}
{% block body %}
									{% if Comentarios %}
									  <ul>

									    {% for Respuesta_Pregunta in Comentarios %}
                      <li><a href="{% url 'foro:resultsH' Preguntaid Respuesta_Pregunta.id %}" class="btn btn-lg btn-block btn-primary" role="button">{{Respuesta_Pregunta.Texto_Respuesta}}</a></li>
									    {% endfor %}
									  </ul>
									{% else %}
									  <h2>'no hay Respuesta_Pregunta'</h2>
									{% endif %}
									{% endblock %}

Openschool/foros/templates/foro/FormPregunta.html
{% extends 'cuentas/index2.html' %}

                {% block body %}
                <div class="container">
                    <h1 style="text-align: center;">¿Cuál es tu pregunta?</h1><br>
                    <form method="post">
                        {% csrf_token %}
                        {{ Pregunta_Form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-info">Crear pregunta</button>
                    </form>
                </div>
                {% endblock %}

Openschool/foros/templates/foro/detail.html
{% extends 'cuentas/index2.html' %}
{% block body %}
	{% if Preguntas %}
	<div class="list-group" style="margin-top: 10px;">
		<a href="{% url 'foro:PreguntaFormA' Materias.id %}" class="list-group-item list-group-item-info" style="text-align: center;">CrearPregunta</a>
    </div>
		 {% for Pregunta in Preguntas %}
		  <div style="margin-top: 10px;">
         	<div >
			 <li style="display: block; text-decoration: none;"><a href="{% url 'foro:results' Pregunta.id %}" style="color:white; " class="btn btn-lg btn-block btn-primary" role="button" >{{Pregunta.Texto_Pregunta}}</a></li>
			</div>
		</div>
		{% endfor %}
	{% else %}
		<h2>'no hay Preguntas'</h2>
	{% endif %}
{% endblock %}

Openschool/foros/templates/foro/index.html
{% extends 'cuentas/index2.html' %}
{% block body %}
<h1 style="text-align: center;">Foros</h1>
            	{% if Carreras %}
                {% for Carrera in Carreras %}
                <div class="pregunta " style="margin-top: 10px">
                	<div class="">
                		<li style="display: block; text-decoration: none;"><a href="{% url 'foro:detail' Carrera.id %}" style="color:white" class="btn btn-lg btn-block btn-primary" role="button">{{Carrera.Nombre_Carrera}}</a></li>
                	</div>
                </div>
                {% endfor %}
                {% else %}
                <h2>'No hay Carreras'</h2>

                {% endif %}
{% endblock %}

Openschool/foros/templates/foro/registro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>OpenSchool</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/estilos.css">

</head>
<body>
	<header>
		<!---------Barra de Menu horizontal-------->
		<div class="container">
	        <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
              <a class="navbar-brand" href="http://localhost:8000/foro">OpenSchool</a>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="#">Noticias</a>
                </li>	

              </ul>
            </nav>

        </div>
	</header>
    <!-----Contenedor de cuerpo de la pagina------>
	<div class="container">
		<div class="row">
			<!-----Primera seccion de la pagina(izquierda)------>
       
			<div class="col-md-3">
       </div>
            <div class="col-md-5">
            	<!-----Segunda seccion de la pagina(centro)------>
              <div class="container" style="border: 2px solid #1a75ff; border-radius: 3px; margin-top: 10px;" >
              {% block content %}
              <!----Formulario------>
                <form action="/registro/" method="post">
                  <!----Etiqueta y caja de texto para nombre------>
                 <label for="Nombre">Nombre:</label>
                 <input id="Nombre" type="text"  class="form-control" placeholder="Ingresa tu nombre" name="Nombre" maxlength="100" value="{{ current_name }}" required/>
                 <!----Etiqueta y caja de texto para apellido paterno------>
                 <label for="Paterno">Apellido Paterno:</label>
                 <input id="Paterno" type="text"  class="form-control" placeholder="Ingresa tu apellido paterno "name="Paterno" maxlength="100" value="{{ current_name }}" requided/>
                 <!----Etiqueta y caja de texto para apellido materno------>
                 <label for="Materno">Apellido Materno:</label>
                 <input id="Materno" type="text"  class="form-control" placeholder="Ingresa tu apellido materno" name="Materno" maxlength="100"  value="{{ current_name }}" required/>
                 <!----Etiqueta y caja de texto para correo electronico------>
                 <label for="Correo">Correo electrónico:</label>
                 <input id="Correo" type="email" name="Correo"  class="form-control" placeholder="Ingresa tu correo electrónico" maxlength="100" value="{{ current_name }}" required/>
                 <!----Etiqueta y caja de texto para contraseña------>
                 <label for="Contraseña">Contraseña:</label>
                 <input id="Contraseña" type="password"  class="form-control" placeholder="Ingresa tu contraseña" name="Contraseña" maxlength="100" value="{{ current_name }}">
                 <!----Etiquetas y checkbox para seleccion de carrera------>
                 <label class="form-check-label" style="margin-left: 15px">
                 <input class="form-check-input" type="checkbox"> Ingeniería Sistemas Computacionales
                 </label>
                 <!----Etiqueta y checkbox para seleccion de carrera------>
                 <label class="form-check-label" style="margin-left: 15px">
                 <input class="form-check-input" type="checkbox"> Ingeniería en Informatica
                 </label>
                 <!----Etiqueta y checkbox para seleccion de carrera------>
                 <label class="form-check-label" style="margin-left: 15px">
                 <input class="form-check-input" type="checkbox"> Ingeniería en Tecnologías de la información y comunicación
                 </label><br><br>
                 <!----Boton de crear cuenta------>
                 <input type="submit" class="btn btn-lg btn-primary" value="Crear cuenta" style="margin-bottom: 10px; margin-left: 140px">
                </form>
              {% endblock %}
              </div>     
            </div>	
            <div class="col-md-4"">
            	
            </div>
	    </div>
	</div>	
</body>
</html>

Openschool/foros/templates/foro/sesion.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>OpenSchool</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/estilos.css">

</head>
<body>
	<header>
		<!---------Barra de Menu horizontal-------->
		<div class="container">
	        <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
              <a class="navbar-brand" href="http://localhost:8000/foro">OpenSchool</a>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="#">Noticias</a>
                </li>

              </ul>
            </nav>

        </div>
	</header>
    <!-----Contenedor de cuerpo de la pagina------>
	<div class="container">
		<div class="row">
			<!-----Primera seccion de la pagina(izquierda)------>

			<div class="col-md-3">
       </div>
            <div class="col-md-5">
            	<!-----Segunda seccion de la pagina(centro)------>
              <div class="container" style="margin-top: 10px;">
              {% block content %}
              <form method="post">
                <button type="submit" class="btn btn-lg btn-primary">Iniciar Sesión</button>
              </form>
              {% endblock %}
              </div>
            </div>
            <div class="col-md-4"">

            </div>
	    </div>
	</div>
</body>
</html>