Openschool/Openschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import  url
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cuentas.urls')),
    path('foros/', include('foros.urls')),
    path('articulos/', include('articulos.urls')),
     path('blog/', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

Openschool/articulos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'articulos'

urlpatterns = [
    path('', views.index, name='index'),
    path('preguntas/<int:Carrera>', views.detail, name='detail'),
    path('CrearPregunta/<int:Materiaid>/', views.ArticuloFormA, name='ArticuloFormA'),
    path('<int:Preguntaid>/results/', views.results, name='results'),
    path('<int:Preguntaid>/results/<int:Comentariosid>', views.resultsH, name='resultsH'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Openschool/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'

urlpatterns = [
path('blog',views.blogs, name='blog'),
]

Openschool/foros/urls.py
from django.urls import path

from . import views
app_name = 'foro'

urlpatterns = [
    path('', views.index, name='index'),
    path('preguntas/<int:Carrera>', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:Preguntaid>/results/<int:Comentariosid>', views.resultsH, name='resultsH'),
    path('<int:Preguntaid>/results/', views.results, name='results'),
    path('CrearPregunta/<int:Materiaid>/', views.PreguntaFormA, name='PreguntaFormA'),
    path('buscar',views.Buscar,name='buscar'),
]

Openschool/articulos/models.py
from django.db import models

# Create your models here.

Openschool/articulos/forms.py
from django import forms
from django.contrib.auth.models import User
from foros.models import Articulo,Comentario_Articulo






class ArticuloForm(forms.ModelForm):

    class Meta:
        model = Articulo
        fields = (
            'Titulo','Pdf_articulo',
        )

        labels={
        'Titulo':'Título',
        }

        widgets={
         'Titulo':forms.TextInput(attrs={'class':'form-control'}),
        }





class RespuestaFormA(forms.ModelForm):

    class Meta:
        model = Comentario_Articulo
        fields = (
            'Texto_Respuesta',
        )

        labels={
        'Texto_Respuesta':'Comentar',
        }

        widgets={
         'Texto_Respuesta':forms.TextInput(attrs={'class':'form-control'}),
        }

Openschool/articulos/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.conf import settings
#
from django.core.files.storage import FileSystemStorage
#impoorta la tabla pregunta
from foros.models import  Carrera,Materia,Articulo,Comentario_Articulo
# Create your views here.
#libreria que manda errores si pasan cosas que no esperamos
#es para ser try cath
from django.http import Http404,HttpResponse
#Creacion del formulario
import datetime
from django.utils import timezone
from .forms import ArticuloForm,RespuestaFormA
from foros.forms import PreguntaForm


def index(request):
    Carreras = Carrera.objects.all()
    return render(request,'articulos/index.html',{'Carreras': Carreras})

def detail(request,Carrera):
    Materias = Materia.objects.get(Carrera_id = Carrera,Nombre_Materia= 'Foro_General')

    Articulos = Articulo.objects.filter(Materia_id= Materias.id)
    Articulos = Articulos.order_by('-Fecha_Publicacion')[:5]

    return render(request,'articulos/detail.html',{'Articulos': Articulos,'Materias': Materias})

def results(request, Preguntaid):
    Comentarios = Comentario_Articulo.objects.filter(Articulo_id= Preguntaid,Comentarios__isnull=True)
    Comentarios = Comentarios.order_by('-Fecha_Publicacion')[:5]
    Articulos= Articulo.objects.get(pk=Preguntaid)
    Respuesta_Form = RespuestaFormA()
    if request.method == 'POST':
        if  request.user.is_authenticated:
            Respuesta_Form = RespuestaFormA(request.POST)
            if Respuesta_Form.is_valid():
                Articulos = Articulo.objects.get(id = Preguntaid)
                Respuesta = Respuesta_Form.save(commit=False)
                Respuesta.user = request.user
                Respuesta.Texto_Respuesta = request.POST['Texto_Respuesta']
                Respuesta.Articulo = Articulos
                Respuesta.save()
                return render(request,'articulos/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'Articulos':Articulos,'Respuesta_Form': Respuesta_Form})
    else:
        Respuesta_Form = RespuestaFormA()

    return render(request,'articulos/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'Articulos':Articulos,'Respuesta_Form': Respuesta_Form})

def resultsH(request,Preguntaid,Comentariosid):
    Comentarios = Comentario_Articulo.objects.filter(Articulo_id= Preguntaid,Comentarios=Comentariosid)
    Comentarios = Comentarios.order_by('-Fecha_Publicacion')[:5]
    ComentarioP= Comentario_Articulo.objects.get(pk=Comentariosid)
    Respuesta_Form = RespuestaFormA()
    if request.method == 'POST':
        if  request.user.is_authenticated:
            Respuesta_Form = RespuestaFormA(request.POST)
            if Respuesta_Form.is_valid():
                Articulos = Articulo.objects.get(id = Preguntaid)
                Respuesta = Respuesta_Form.save(commit=False)
                Respuesta.user = request.user
                Respuesta.Comentarios = ComentarioP
                Respuesta.Texto_Respuesta = request.POST['Texto_Respuesta']
                Respuesta.Articulo = Articulos
                Respuesta.save()
                return render(request,'articulos/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'ComentarioP':ComentarioP,'Respuesta_Form': Respuesta_Form})
    return render(request,'articulos/Comentarios.html',{'Comentarios': Comentarios,'Preguntaid':Preguntaid,'ComentarioP':ComentarioP,'Respuesta_Form': Respuesta_Form})


def ArticuloFormA(request,Materiaid):
    Articulos = Articulo.objects.filter(Materia_id= Materiaid)
    Articulos = Articulos.order_by('-Fecha_Publicacion')[:5]
    Pregunta_Form = ArticuloForm()
    args = {'Pregunta_Form': Pregunta_Form}
    if request.method == 'POST':
        form = ArticuloForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            Materias = Materia.objects.get(id = Materiaid)
            Preguntad = form.save(commit=False)
            Preguntad.user = request.user
            Preguntad.Texto_Pregunta = request.POST['Titulo']
            Preguntad.Materia = Materias
            Preguntad.Pdf_articulo = request.FILES['Pdf_articulo']
            Preguntad.save()
            Articulos = Articulo.objects.filter(Materia_id= Materiaid)
            Articulos = Articulos.order_by('-Fecha_Publicacion')[:5]
            return render(request,'articulos/detail.html',{'Articulos': Articulos,'Materias': Materias})
    else:
        Pregunta_Form = ArticuloForm()
        args = {'Pregunta_Form': Pregunta_Form}
    return render(request,'articulos/ArticulosForm.html',args)

Openschool/articulos/templates/articulos/ArticulosForm.html
{% extends 'cuentas/index2.html' %}

                {% block body %}
                <div class="container">
                    <h1>¿Cuál es el artículo que quieres subir?</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ Pregunta_Form.as_p }}
                        <button type="submit" class="btn btn-block btn-lg btn-info">Subir artículo</button>
                    </form>
                </div>
                {% endblock %}

Openschool/articulos/templates/articulos/Comentarios.html
{% extends 'cuentas/index2.html' %}
{% block body %}
{% if Articulos %}
<div class="card bg-primary" style="margin-top: 10px;">
  <div class="card-body">
  <h2 style="color:white;">{{Articulos.Titulo}}</h2>
  </div>
</div>
{% else %}
<div class="card bg-primary" style="margin-top: 10px;">
  <div class="card-body">
  <h2 style="color:white;">{{ComentarioP.Texto_Respuesta}}</h2>
  </div>
</div>
{% endif %}
	{% if Comentarios %}
      <div class="list-group-item list-group-item-primary">
     {% for Respuesta_Pregunta in Comentarios %}
        <li style="display: block; text-decoration: none;"><a href="{% url 'articulos:resultsH' Preguntaid Respuesta_Pregunta.id %}" class="btn btn-lg btn-block btn-info" role="button" style="text-align: left;">{{Respuesta_Pregunta.Texto_Respuesta}}</a></li>
      </div>
      <div class="list-group-item list-group-item-primary">
        <form method="post">
     {% endfor %}
        {% csrf_token %}
        {{ Respuesta_Form.as_p }}
        <button type="submit" class="btn btn-lg btn-info">Submit</button>
        </form>
      </div>
	{% else %}
	<div class="list-group-item list-group-item-primary">
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ Respuesta_Form.as_p }}
        <button type="submit" class="btn btn-lg btn-info">Submit</button>
      </form>
    </div>
  </div>

	{% endif %}
{% endblock %}

Openschool/articulos/templates/articulos/ComentariosH.html
{% extends 'cuentas/index2.html' %}
{% block body %}
									{% if Comentarios %}
									  <ul>

									    {% for Respuesta_Pregunta in Comentarios %}
                      <li><a href="{% url 'foro:resultsH' Preguntaid Respuesta_Pregunta.id %}" class="btn btn-lg btn-block btn-primary" role="button">{{Respuesta_Pregunta.Texto_Respuesta}}</a></li>
									    {% endfor %}
									  </ul>
									{% else %}
									  <h2>'no hay Respuesta_Pregunta'</h2>
									{% endif %}
									{% endblock %}

Openschool/articulos/templates/articulos/detail.html
{% extends 'cuentas/index2.html' %}
{% block body %}
<div class="list-group" style="margin-top: 10px;">
	<a href="{% url 'articulos:ArticuloFormA' Materias.id %}" class="list-group-item list-group-item-info" style="text-align: center;">Crear Articulo</a>
	</div>
	{% if Articulos %}
		 {% for Articulo in Articulos %}
		  <div style="margin-top: 10px;">
         	<div >
			 <li style="display: block; text-decoration: none;"><a href="{% url 'articulos:results' Articulo.id %}" style="color:white; " class="btn btn-lg btn-block btn-primary" role="button" >{{Articulo.Titulo}}</a></li>

			</div>
			<embed src="{{Articulo.Pdf_articulo.url}}" width="800" height="800" type='application/pdf'>
		</div>
		{% endfor %}
	{% else %}
		<h2>'no hay Articulos'</h2>
	{% endif %}
{% endblock %}

Openschool/articulos/templates/articulos/index.html
{% extends 'cuentas/index2.html' %}
{% block body %}
    <h1 style="text-align: center;">Artículos</h1>
            	{% if Carreras %}
                {% for Carrera in Carreras %}
                <div class="pregunta " style="margin-top: 10px">
                	<div class="">
                		<li style="display: block; text-decoration: none;"><a href="{% url 'articulos:detail' Carrera.id %}" style="color:white" class="btn btn-lg btn-block btn-primary" role="button">{{Carrera.Nombre_Carrera}}</a></li>
                	</div>
                </div>
                {% endfor %}
                {% else %}
                <h2>'No hay Carreras'</h2>

                {% endif %}
{% endblock %}